"""descripcion del cambio

Revision ID: f7ea695442d1
Revises: 743800c42801
Create Date: 2025-11-24 07:54:20.508590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7ea695442d1'
down_revision = '743800c42801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tallas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tiendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.drop_table('empleadas')
    with op.batch_alter_table('orden_items', schema=None) as batch_op:
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('tienda_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('talla_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_productos_sku'), ['sku'], unique=True)
        batch_op.create_foreign_key(None, 'tallas', ['talla_id'], ['id'])
        batch_op.create_foreign_key(None, 'tiendas', ['tienda_id'], ['id'])
        batch_op.drop_column('talla')
        batch_op.drop_column('tienda')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tienda', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('talla', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_productos_sku'))
        batch_op.drop_column('talla_id')
        batch_op.drop_column('tienda_id')
        batch_op.drop_column('sku')

    with op.batch_alter_table('orden_items', schema=None) as batch_op:
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('empleadas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('empleadas_pkey'))
    )
    op.drop_table('tiendas')
    op.drop_table('tallas')
    # ### end Alembic commands ###
